FROM python:3.7-slim

RUN apt-get update -y && apt-get install -y \
    tesseract-ocr-fra \
    libfreeimage3 \
    enchant \
    libpoppler-cpp0v5 \
    aspell-fr \
    libtesseract4

# Copy artifacts
COPY ./code/build/soduco-py37-0.1.1-Linux.tar.gz extract.sh /app/

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

# Set extra lib dir and locale
ENV LD_LIBRARY_PATH=/app/lib LC_ALL=C

WORKDIR /app
